apiVersion: apps/v1
kind: Deployment
metadata:
  name: Azure-02
spec:
  template:
    spec:
      containers:
      - name: Azure-02
        env:
        - name: ENVIRONMENT
          value: development
        - name: DEBUG
          value: "true"
