apiVersion: apps/v1
kind: Deployment
metadata:
  name: Azure-02
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: Azure-02
        env:
        - name: ENVIRONMENT
          value: dev
        - name: LOG_LEVEL
          value: DEBUG
