# Azure Workload Identity for AKS-01
# Enables pods to authenticate to Azure services using managed identity

apiVersion: v1
kind: ServiceAccount
metadata:
  name: AKS-01-identity
  namespace: AKS-01
  labels:
    app.kubernetes.io/name: AKS-01
  annotations:
    # Replace with your Azure managed identity client ID
    azure.workload.identity/client-id: "<managed-identity-client-id>"
---
# Pod label for workload identity
# Add this label to pods that need Azure access:
# azure.workload.identity/use: "true"

# Example: FederatedIdentityCredential (Azure CLI/Terraform)
# az identity federated-credential create \
#   --name AKS-01-federated \
#   --identity-name AKS-01-identity \
#   --resource-group <resource-group> \
#   --issuer <aks-oidc-issuer> \
#   --subject system:serviceaccount:AKS-01:AKS-01-identity
