# AKS-04 - AKS Infrastructure
# Generated by project-initializer
# Default sizing

locals {
  project_name     = var.project_name
  environment      = var.environment
  location         = var.location
  resource_prefix  = "${var.project_name}-${var.environment}"
  
  common_tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
    Purpose     = "elasticsearch-cluster"
  }
}

# Resource Group
resource "azurerm_resource_group" "main" {
  name     = "rg-${local.resource_prefix}"
  location = local.location
  tags     = local.common_tags
}

# Networking
module "networking" {
  source = "./modules/networking"
  
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  resource_prefix     = local.resource_prefix
  
  vnet_address_space    = var.vnet_address_space
  aks_subnet_prefix     = var.aks_subnet_prefix
  private_subnet_prefix = var.private_subnet_prefix
  
  tags = local.common_tags
}

# Azure Container Registry
module "acr" {
  source = "./modules/acr"
  
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  resource_prefix     = local.resource_prefix
  
  sku = var.acr_sku
  
  tags = local.common_tags
}

# Monitoring (Log Analytics + Azure Monitor)
module "monitoring" {
  source = "./modules/monitoring"
  
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  resource_prefix     = local.resource_prefix
  
  log_retention_days = var.log_retention_days
  
  tags = local.common_tags
}

# Storage (for ES snapshots)
module "storage" {
  source = "./modules/storage"
  
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  resource_prefix     = local.resource_prefix
  
  snapshot_container_name = var.snapshot_container_name
  snapshot_storage_gb     = var.snapshot_storage_gb
  
  tags = local.common_tags
}

# AKS Cluster
module "aks" {
  source = "./modules/aks"
  
  resource_group_name = azurerm_resource_group.main.name
  location            = local.location
  resource_prefix     = local.resource_prefix
  
  kubernetes_version = var.kubernetes_version
  
  # Networking
  vnet_subnet_id = module.networking.aks_subnet_id
  
  # System node pool
  system_node_count = var.system_node_count
  system_vm_size    = var.system_vm_size
  
  # ES Hot tier
  es_hot_node_count    = var.es_hot_node_count
  es_hot_vm_size       = var.es_hot_vm_size
  es_hot_disk_size_gb  = var.es_hot_disk_size_gb
  
  # ES Cold tier
  es_cold_enabled      = var.es_cold_enabled
  es_cold_node_count   = var.es_cold_node_count
  es_cold_vm_size      = var.es_cold_vm_size
  es_cold_disk_size_gb = var.es_cold_disk_size_gb
  
  # ES Frozen tier
  es_frozen_enabled      = var.es_frozen_enabled
  es_frozen_node_count   = var.es_frozen_node_count
  es_frozen_vm_size      = var.es_frozen_vm_size
  es_frozen_disk_size_gb = var.es_frozen_disk_size_gb
  
  # Monitoring
  log_analytics_workspace_id = module.monitoring.log_analytics_workspace_id
  
  # ACR integration
  acr_id = module.acr.acr_id
  
  tags = local.common_tags
}
