# Azure Workload Identity for Azure-03
# Enables pods to authenticate to Azure services using managed identity

apiVersion: v1
kind: ServiceAccount
metadata:
  name: Azure-03-identity
  namespace: Azure-03
  labels:
    app.kubernetes.io/name: Azure-03
  annotations:
    # Replace with your Azure managed identity client ID
    azure.workload.identity/client-id: "<managed-identity-client-id>"
---
# Pod label for workload identity
# Add this label to pods that need Azure access:
# azure.workload.identity/use: "true"

# Example: FederatedIdentityCredential (Azure CLI/Terraform)
# az identity federated-credential create \
#   --name Azure-03-federated \
#   --identity-name Azure-03-identity \
#   --resource-group <resource-group> \
#   --issuer <aks-oidc-issuer> \
#   --subject system:serviceaccount:Azure-03:Azure-03-identity
