apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Azure-02
  namespace: argocd
  labels:
    app.kubernetes.io/name: Azure-02
    app.kubernetes.io/component: appproject
  # Finalizer to prevent accidental deletion
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Elasticsearch cluster Az-02"
  
  # Source repositories
  sourceRepos:
    - "https://github.com/org/Azure-02.git"
    - "https://helm.elastic.co"
    - "https://charts.bitnami.com/bitnami"
  
  # Destination clusters and namespaces
  destinations:
    # Dev environment
    - namespace: "Azure-02-dev"
      server: "https://kubernetes.default.svc"
    # Staging environment
    - namespace: "Azure-02-staging"
      server: "https://kubernetes.default.svc"
    # Production environment
    - namespace: "Azure-02-production"
      server: "https://kubernetes.default.svc"
    # ArgoCD namespace for app-of-apps
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
  
  # Cluster resource allowlist
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "elasticsearch.k8s.elastic.co"
      kind: Elasticsearch
    - group: "kibana.k8s.elastic.co"
      kind: Kibana
    - group: "agent.k8s.elastic.co"
      kind: Agent
  
  # Namespace resource denylist (security)
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
  
  # Roles for project members
  roles:
    - name: developer
      description: "Developer access - can sync applications"
      policies:
        - p, proj:Azure-02:developer, applications, get, Azure-02/*, allow
        - p, proj:Azure-02:developer, applications, sync, Azure-02/*, allow
      groups:
        - developers
    
    - name: admin
      description: "Admin access - full control"
      policies:
        - p, proj:Azure-02:admin, applications, *, Azure-02/*, allow
        - p, proj:Azure-02:admin, repositories, *, Azure-02/*, allow
      groups:
        - admins
