apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: AKS-01
  namespace: AKS-01
  labels:
    app.kubernetes.io/name: AKS-01
    app.kubernetes.io/component: kibana
spec:
  version: 8.17.0
  count: 1
  
  elasticsearchRef:
    name: AKS-01
  
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
