# Elasticsearch Cluster Resource Requirements
# Source: Sizing Report (Custom)
# Platform: Azure AKS
# Health Score: 0/100

apiVersion: v1
kind: ConfigMap
metadata:
  name: es-sizing-config
  namespace: Azure-02
data:
  profile: "custom"
  source: "sizing_report"
  platform: "aks"
  
---
# Resource Totals (from sizing report)
#
# Total Nodes: 0
# Total vCPU: 0
# Total RAM: 0 GB
# Total Local Disk: 0 GB
# Snapshot Storage: 76500.0 GB
#
# ============================================================
# Tier Breakdown
# ============================================================
#
# HOT TIER (primary indexing):
#   Nodes: 0
#   Memory: N/A per node
#   CPU: N/A cores per node
#   Storage: N/A per node
#
# ============================================================
# Use these values to request cluster resources from infrastructure team
# ============================================================
