# Security Context Constraints for Elasticsearch on OpenShift
# ECK requires privileged SCCs for the init containers
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: AKS-04-elasticsearch
  labels:
    app.kubernetes.io/name: AKS-04
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:AKS-04:default
  - system:serviceaccount:AKS-04:elastic-agent
---
# Grant SCC to service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: AKS-04-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:AKS-04-elasticsearch
subjects:
  - kind: ServiceAccount
    name: default
    namespace: AKS-04
