apiVersion: apps/v1
kind: Deployment
metadata:
  name: AKS-04
spec:
  template:
    spec:
      containers:
      - name: AKS-04
        env:
        - name: ENVIRONMENT
          value: development
        - name: DEBUG
          value: "true"
