# Azure Workload Identity for Azure-02
# Enables pods to authenticate to Azure services using managed identity

apiVersion: v1
kind: ServiceAccount
metadata:
  name: Azure-02-identity
  namespace: Azure-02
  labels:
    app.kubernetes.io/name: Azure-02
  annotations:
    # Replace with your Azure managed identity client ID
    azure.workload.identity/client-id: "<managed-identity-client-id>"
---
# Pod label for workload identity
# Add this label to pods that need Azure access:
# azure.workload.identity/use: "true"

# Example: FederatedIdentityCredential (Azure CLI/Terraform)
# az identity federated-credential create \
#   --name Azure-02-federated \
#   --identity-name Azure-02-identity \
#   --resource-group <resource-group> \
#   --issuer <aks-oidc-issuer> \
#   --subject system:serviceaccount:Azure-02:Azure-02-identity
