apiVersion: apps/v1
kind: Deployment
metadata:
  name: AKS-01
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: AKS-01
        env:
        - name: ENVIRONMENT
          value: staging
        - name: LOG_LEVEL
          value: DEBUG
