apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: AKS-01
  labels:
    app.kubernetes.io/name: AKS-01
    app.kubernetes.io/component: elastic-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent-AKS-01
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "events", "services", "configmaps", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/metrics"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent-AKS-01
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: AKS-01
roleRef:
  kind: ClusterRole
  name: elastic-agent-AKS-01
  apiGroup: rbac.authorization.k8s.io
