apiVersion: apps/v1
kind: Deployment
metadata:
  name: AKS-04
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: AKS-04
        env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: INFO
