apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: AKS-04
  namespace: AKS-04
  annotations:
    # OpenShift: Allow ECK to manage security context
    eck.k8s.elastic.co/downward-node-labels: "topology.kubernetes.io/zone"
  labels:
    app.kubernetes.io/name: AKS-04
    app.kubernetes.io/component: elasticsearch
spec:
  version: 8.17.0
  
  # HTTP configuration
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  
  # Node sets
  nodeSets:
    # Master nodes (dedicated)
    - name: master
      count: 3
      config:
        node.roles: ["master"]
        # Disable machine learning on master nodes
        xpack.ml.enabled: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                  cpu: "1"
                limits:
                  memory: 2Gi
                  cpu: "2000m"
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

    # Hot tier - data nodes (ingest, recent data)
    - name: hot
      count: 3
      config:
        node.roles: ["data_hot", "data_content", "ingest", "transform"]
        # Hot tier node attributes
        node.attr.data: hot
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: "2"
                limits:
                  memory: 8Gi
                  cpu: "4"
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        elasticsearch.k8s.elastic.co/cluster-name: AKS-04
                        elasticsearch.k8s.elastic.co/node-data: "true"
                    topologyKey: topology.kubernetes.io/zone
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: standard

    # =========================================================================
    # WARM TIER (Optional) - Uncomment to enable
    # Use for data that is queried less frequently (7-30 days old typically)
    # =========================================================================
    # - name: warm
    #   count: 3
    #   config:
    #     node.roles: ["data_warm"]
    #     node.attr.data: warm
    #   podTemplate:
    #     spec:
    #       containers:
    #         - name: elasticsearch
    #           resources:
    #             requests:
    #               memory: 16Gi
    #               cpu: "4"
    #             limits:
    #               memory: 16Gi
    #               cpu: "8"
    #       initContainers:
    #         - name: sysctl
    #           securityContext:
    #             privileged: true
    #             runAsUser: 0
    #           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    #   volumeClaimTemplates:
    #     - metadata:
    #         name: elasticsearch-data
    #       spec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 1000Gi
    #         storageClassName: standard

    # =========================================================================
    # COLD TIER (Optional) - Uncomment to enable
    # Use for data that is rarely queried (30-90 days old typically)
    # Lower storage cost, higher storage:RAM ratio
    # =========================================================================
    # - name: cold
    #   count: 3
    #   config:
    #     node.roles: ["data_cold"]
    #     node.attr.data: cold
    #   podTemplate:
    #     spec:
    #       containers:
    #         - name: elasticsearch
    #           resources:
    #             requests:
    #               memory: 16Gi
    #               cpu: "4"
    #             limits:
    #               memory: 16Gi
    #               cpu: "8"
    #       initContainers:
    #         - name: sysctl
    #           securityContext:
    #             privileged: true
    #             runAsUser: 0
    #           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    #   volumeClaimTemplates:
    #     - metadata:
    #         name: elasticsearch-data
    #       spec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 2000Gi
    #         storageClassName: standard

    # =========================================================================
    # FROZEN TIER (Optional) - Uncomment to enable
    # Use for archival data with searchable snapshots (90+ days typically)
    # Requires snapshot repository (S3/GCS/Azure Blob) configured
    # =========================================================================
    # - name: frozen
    #   count: 1
    #   config:
    #     node.roles: ["data_frozen"]
    #     node.attr.data: frozen
    #     # Searchable snapshots local cache
    #     xpack.searchable.snapshot.shared_cache.size: 90%
    #   podTemplate:
    #     spec:
    #       containers:
    #         - name: elasticsearch
    #           resources:
    #             requests:
    #               memory: 32Gi
    #               cpu: "8"
    #             limits:
    #               memory: 32Gi
    #               cpu: "16"
    #       initContainers:
    #         - name: sysctl
    #           securityContext:
    #             privileged: true
    #             runAsUser: 0
    #           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    #   volumeClaimTemplates:
    #     - metadata:
    #         name: elasticsearch-data
    #       spec:
    #         accessModes:
    #           - ReadWriteOnce
    #         resources:
    #           requests:
    #             storage: 2400Gi  # Local cache for searchable snapshots
    #         storageClassName: standard
